### ISSUE TITLE
loadClerkContract: Empty value (0x) returned from contract

### ISSUE THREAD

**Issue by Zied-Guesmi** [iExecBlockchainComputing/iexec-core#173]
With the new version of poco-chain `iexechub/poco-chain:legacy-11a934b690bd4c020a90186bf6a10ecb47a2fe4d`, the core can not load Clerk address from iexecHubABILegacy contract, which then causes a nullPointerException when creating 'dealWatcherService' bean.

The complete exception:

<img width="1316" alt="screen shot 2019-02-05 at 10 18 31" src="https://user-images.githubusercontent.com/26070035/52263442-7a166300-292f-11e9-8fd6-2e79d6af5bd3.png">

**Comment by jeremyjams** [comment]
Yes, addreses did changed.
Here is it: https://github.com/iExecBlockchainComputing/iexec-core/pull/176
