### ISSUE TITLE
Make possible to override default gasPrice values

### ISSUE THREAD

**Issue by jeremyjams** [iExecBlockchainComputing/iexec-core#194]
Possible implementations for Core & Worker:

**1 - Read a fixed value of the gasPrice set in the configuration file** 

Ex: 10Gwei
(+) pros: You know what you get
(-) cons: Doesn't follow market fees

**2 - Read a gasPrice multiplier set in the configuration file coupled with an estimate gasPrice from eth node at runtime** 

Ex: 10Gwei * 1.50 for faster transactions
(+) pros: You follow market fees
(-) cons: What if the estimateGasPrice from the node goes crazy ? (Your soft will hang or you will pay way to much for super fast txs you don't need)

What do you think?

**Comment by Zied-Guesmi** [comment]
We can mix them, a real-time estimated gas price with a threshold, so it does not exceed that fixed value.

**Comment by Ugo** [comment]
Right, a fixed one doesn't really make sense. I agree with @Zied-Guesmi, the second solution with a max value seems better.

**Comment by jeremyjams** [comment]
Done in #200 :)
