### ISSUE TITLE
Cannot update replicate, bad wokfow transition [currentStatus:COMPLETED, newStatus:WORKER_LOST chainTaskId:, walletAddress:, details:null]

### ISSUE THREAD

**Issue by zguesmi** [iExecBlockchainComputing/iexec-core#346]

**Comment by jeremyjams** [comment]
Fixed with https://github.com/iExecBlockchainComputing/iexec-core/pull/393.
(1) Workers are freed (not participating anymore) when replicate is COMPLETED or FAILED.
(2) Replicates of lost workers won't be updated to WORKER_LOST if already in WORKER_LOST, COMPLETED or FAILED.
