### ISSUE TITLE
Getlastblockfailed - blockchain node seems unsync 

### ISSUE THREAD

**Issue by borgqueenx** [iExecBlockchainComputing/iexec-core#347]
![Screenshot_20191225-005526_Far Commander](https://user-images.githubusercontent.com/20416925/71443543-c7e4b700-270b-11ea-8f4f-ea3eb79821ad.jpg)

See image. This sometimes happens to my workers...

**Comment by zguesmi** [comment]
Hi @borgqueenx please report worker-related issues here https://github.com/iExecBlockchainComputing/iexec-worker.

Thanks,
